In [1]:
import tensorflow as tf

In [2]:
con=tf.constant(44)

In [3]:
con

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [4]:
constant_mat= tf.constant([[1,3],[2,4]], dtype=tf.int32)

In [5]:
constant_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]])>

In [6]:
a=tf.ones([3,3], dtype=tf.int32)

In [7]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

In [8]:
-1*tf.ones(shape=(2,3), dtype=tf.int32)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

In [9]:
tf.zeros(shape=(5,5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [10]:
b=tf.constant([[1,2,3],[6,7,8]], dtype=tf.int32)
c=tf.constant([[4,3,2],[4,3,2]], dtype=tf.int32)

In [11]:
b+c

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  5,  5],
       [10, 10, 10]])>

In [12]:
tf.subtract(b,c)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-3, -1,  1],
       [ 2,  4,  6]])>

#  Random Constant

In [13]:
tf.random.normal(shape=(2,2),mean=0, stddev=1.0)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.6866737 , -0.7545305 ],
       [-0.5946944 ,  0.42741606]], dtype=float32)>

In [14]:
tf.random.uniform([2,2], minval=0, maxval=10)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.8738651, 7.3238015],
       [5.6302824, 1.8214357]], dtype=float32)>

# Variables

In [15]:
var1=tf.Variable([[1,2,3],[6,7,8]])

In [23]:
var2=tf.Variable(40)

In [24]:
var2.assign(33)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=33>

In [25]:
var2

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=33>

In [26]:
type(var2)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [27]:
var2=30

In [28]:
type(var2)

int

In [29]:
var1.assign([[14,2,3],[6,7,8]])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[14,  2,  3],
       [ 6,  7,  8]])>

In [30]:
var1[1,1].assign(34) 

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[14,  2,  3],
       [ 6, 34,  8]])>

In [31]:
var1.assign([[14,2,3],[6,7,8],[3,3,3]])

ValueError: Cannot assign value to variable ' Variable:0': Shape mismatch.The variable shape (2, 3), and the assigned value shape (3, 3) are incompatible.

In [33]:
var3=tf.Variable([[1,2,3],[6,7,8]])

In [34]:
var3.shape

TensorShape([2, 3])

In [35]:
tf.reshape(var3, [3,2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 6],
       [7, 8]])>

# Mathematical operations

In [36]:
var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[14,  2,  3],
       [ 6, 34,  8]])>

In [37]:
tf.square(var1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 196,    4,    9],
       [  36, 1156,   64]])>

# Broadcasting inTF

In [38]:
scaler = 4
scaler * var1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 56,   8,  12],
       [ 24, 136,  32]])>

# Matrix Multiplication

In [39]:
mat_x=tf.constant([[1,2,3]])
mat_y=tf.constant([[3,4,3]])

In [40]:
print(mat_x.shape)
print(mat_y.shape)

(1, 3)
(1, 3)


In [41]:
tf.matmul(mat_x,mat_y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [1,3], In[1]: [1,3] [Op:MatMul] name: 

In [ ]:
tf.matmul(mat_x,tf.transpose(mat_y))

In [ ]:
mat_x@tf.transpose(mat_y)

In [ ]:
mat_x * mat_y 

#  Type Casting

changes the dtype of the variables

In [42]:
mat_x.dtype

tf.int32

In [43]:
tf.cast(mat_x, dtype=tf.int16) # can be used in quantizing a model to save the space in the memory allocation

<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[1, 2, 3]], dtype=int16)>

In [44]:
mat_x.dtype

tf.int32

# Ragged Tesnors

Nested variable length arrays

In [45]:
ragg=tf.ragged.constant([[1,2,3,4,5],[1],[9,8,7]])

In [46]:
ragg.shape

TensorShape([3, None])

In [47]:
ragg[0].shape

TensorShape([5])

In [48]:
ragg[1].shape

TensorShape([1])

#  Squared difference of tensors

In [49]:
var_a=[1,2,3,4,5,6]
var_b=2

tf.math.squared_difference(var_a,var_b)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  0,  1,  4,  9, 16])>

In [50]:
pred=[1,2,3,4,5,6]
actual=[1,1,1,1,1,1]

tf.math.squared_difference(pred,actual)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25])>

#  Calculate mean

In [51]:
num=tf.constant([[1,2],[3,4]], dtype=tf.float32)
num

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [52]:
tf.reduce_mean(num) # mean of all the element

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [53]:
tf.reduce_mean(num, axis=0)  # mean of row element

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [54]:
tf.reduce_mean(num, axis=1)  # mean of Column element

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [55]:
tf.reduce_mean(num, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>

In [56]:
tf.reduce_mean(num, axis=1, keepdims=False)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

# CheckPointing

checkpointing is use restore the matrix values

In [57]:
var1= tf.Variable(5*tf.ones([5,5]))

In [58]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

In [59]:
ckpt=tf.train.Checkpoint(var=var1)
savepath=ckpt.save("./vars.ckpt")

In [60]:
var1.assign(tf.zeros([5,5]))

<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [61]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

#  restore the value

In [62]:
ckpt.restore(savepath)

In [63]:
var1

<tf.Variable 'Variable:0' shape=(5, 5) dtype=float32, numpy=
array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]], dtype=float32)>

#  tf.function

z=X^3 * 6 + y^3

In [64]:
def f1(x,y):
    input_var=tf.multiply(x**3, 6) + y**3
    return tf.reduce_mean(input_tensor=input_var)

In [65]:
func= tf.function(f1)  # Tensorflow optimization  "Parallelization"

In [66]:
x=tf.constant([3., -4.])
y=tf.constant([1.,4.])

In [67]:
f1(x,y)  # using simple python function

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [68]:
func(x,y)  # using tensorflow function

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

In [69]:
@tf.function ## tf decorator function it tries to be a wrapper of below function & without changing the definition of the function.

def f2(x,y):
    input_var=tf.multiply(x**3, 6) + y**3
    return tf.reduce_mean(input_tensor=input_var)


In [70]:
f2(x,y)  # behave as a tensor flow function

<tf.Tensor: shape=(), dtype=float32, numpy=-78.5>

#  Example of decorator

In [71]:
def print_me():
    print("Hi DL")

In [72]:
print_me()

Hi DL


In [73]:
print("--"*30)
print_me()
print("--"*30)

------------------------------------------------------------
Hi DL
------------------------------------------------------------


In [74]:
def decorate_it(input_func):# wrapper func it will take the definition of input funcand return the decorated func
    def decorated_func():
        print("--"*30)
        input_func()
        print("--"*30)
        
        
    return decorated_func


In [75]:
decorated_func=decorate_it(print_me)
decorated_func()

------------------------------------------------------------
Hi DL
------------------------------------------------------------


In [76]:
@decorate_it
def print_me2():
    print("Hi DL")

In [77]:
print_me2()  #best method

------------------------------------------------------------
Hi DL
------------------------------------------------------------


In [78]:
@decorate_it
def print_my_name():
    print('Arvind')

In [79]:
print_my_name()

------------------------------------------------------------
Arvind
------------------------------------------------------------


In [82]:
@decorate_it
def mynameee():
    print('Avi')

In [83]:
mynameee()

------------------------------------------------------------
Avi
------------------------------------------------------------


#  Calculation of Gradients in tf

In [84]:
x=tf.random.normal(shape=(2,2)) # normal creates a constant value by default.
y=tf.random.normal(shape=(2,2))

#  lets say we have a function of x &y 

# f(x,y)=sqrt{(x^2 + y^2)}
# nabla/gradient {f(x,y)}=  (df/dx)i + (df/dy)j   partial derivative

In [85]:
with tf.GradientTape() as tape:  # help you to calculate the gradient
    tape.watch(x)  # watch the variable x
    f=tf.sqrt(tf.square(x) + tf.square(y))  # function definition
    
    df_dx= tape.gradient(f,x) # derivate of f w.r.t x
    print(df_dx)

tf.Tensor(
[[-0.6670661  -0.9292622 ]
 [ 0.76460296  0.4972051 ]], shape=(2, 2), dtype=float32)


In [86]:
#tf.wartch is only need when x & y are  not variables

with tf.GradientTape() as tape:  # help you to calculate the gradient
    tape.watch(x) # I want to calculate grad w.r.t 'x'
    tape.watch(y) # I want to calculate grad w.r.t 'y'
    f=tf.sqrt(tf.square(x) + tf.square(y))  # function definition
    
    df_dx, df_dy= tape.gradient(f,[x,y]) # partial derivates of 'f' w.r.t 'x' & 'y' 
    print("df_dx",df_dx)
    print("df_dy",df_dy)

df_dx tf.Tensor(
[[-0.6670661  -0.9292622 ]
 [ 0.76460296  0.4972051 ]], shape=(2, 2), dtype=float32)
df_dy tf.Tensor(
[[-0.7449985  -0.36942068]
 [-0.6445015   0.867633  ]], shape=(2, 2), dtype=float32)


In [87]:
x1=tf.Variable(tf.random.normal(shape=(2,2)))
y1=tf.Variable(tf.random.normal(shape=(2,2)))

In [88]:
with tf.GradientTape() as tape:  # help you to calculate the gradient
    #tape.watch(x) # I want to calculate grad w.r.t 'x'
    #tape.watch(y) # I want to calculate grad w.r.t 'y'
    f=tf.sqrt(tf.square(x1) + tf.square(y1))  # function definition
    
    df_dx, df_dy= tape.gradient(f,[x1,y1]) # partial derivates of 'f' w.r.t 'x' & 'y' 
    print("df_dx",df_dx)
    print("df_dy",df_dy)

df_dx tf.Tensor(
[[ 0.94413537 -0.8564534 ]
 [ 0.730928    0.52012444]], shape=(2, 2), dtype=float32)
df_dy tf.Tensor(
[[-0.32955804  0.5162244 ]
 [-0.6824546   0.8540906 ]], shape=(2, 2), dtype=float32)


In [ ]:
x2=tf.Variable(3.)
y2=tf.Variable(2.)
with tf.GradientTape() as tape:
    f=tf.sqrt(tf.square(x2) + tf.square(y2))
    
    df_dx, df_dy= tape.gradient(f,[x2,y2])
    print("df_dx",df_dx)
    print("df_dy",df_dy)
              

In [ ]:
x2/tf.sqrt(tf.square(x2) + tf.square(y2))  # verify

In [ ]:
y2/tf.sqrt(tf.square(x2) + tf.square(y2))

# Simple Linear Regression

f(x)= W.b + b

In [ ]:
TRUE_W=3.0
TRUE_B=2.0
NUM_EXAMPLES=1000
x= tf.random.normal(shape=[NUM_EXAMPLES])

In [ ]:
noise = tf.random.normal(shape=[NUM_EXAMPLES])

In [ ]:
y=x*TRUE_W+TRUE_B+noise

In [ ]:
import matplotlib.pyplot as plt

plt.scatter(x,y,c='r')
plt.show()

#  Let's define a model

In [ ]:
class MyModel(tf.Module):  # define class and inherit tf.Module
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        
        self.w=tf.Variable(5.0)
        self.b=tf.Variable(0.0)
        
    def __call__(self,x):
        return self.w*x +self.b

In [ ]:
model=MyModel()

In [ ]:
model(5)

In [ ]:
model.b
model.w
model.variables

In [ ]:
def MSE_loss(target_y,predicted_y):
    error=target_y - predicted_y
    squared_error=tf.square(error)
    mse=tf.reduce_mean(squared_error)
    return mse

In [ ]:
plt.scatter(x,y,c='b')
pred_y=model(x)  # without training
plt.scatter(x,pred_y,c='r')
plt.show()

In [ ]:
current_loss=MSE_loss(y,model(x))
current_loss.numpy()

#  training function

In [ ]:
def train1(model,x,y,learning_rate):

    with tf.GradientTape() as tape:
        current_loss=MSE_loss(y, model(x))
        
    dc_dw,dc_db = tape.gradient(current_loss, [model.w, model.b])
    
    model.w.assign_sub(learning_rate* dc_dw)  # w=w-learning_rate(de/dw)
    model.b.assign_sub(learning_rate* dc_db) ## b=b-learning_rate(de/db)

In [ ]:
model=MyModel()

ws,bs =[], []

epochs=10
learning_rate=0.1

w=model.w.numpy()
b=model.b.numpy()

init_loss = MSE_loss(y,model(x)).numpy()

print(f"initial W:{w}, initial bias: {b}, initial loss: {init_loss}")

In [ ]:
for epoch in range(epochs):
    train1(model,x,y,learning_rate)
    
    ws.append(model.w.numpy())
    bs.append(model.b.numpy())
    
    current_loss=MSE_loss(y,model(x))
    
    print(f"for epoch: {epoch}, w:{ws[-1]}, b:{bs[-1]}, current_loss:{current_loss}")


In [ ]:
plt.plot(range(epochs), Ws, 'r', range(epochs), bs, "b")

plt.plot([TRUE_W] * epochs, "r--", [TRUE_B] * epochs, "b--")

plt.legend(["W", "b", "True W", "True B"])

plt.show()

In [ ]:
plt.scatter(x, y, c="b")

pred_y = model(x) ## after training
plt.scatter(x, pred_y, c="r") 

plt.show()